import {
  faArrowsUpDown,
  faBan,
  faBorderAll,
  faCirclePlay,
  faComment,
  faCommentSlash,
  faCompass,
  faCrown,
  faEnvelope,
  faFaceSmile,
  faGem,
  faGift,
  faHighlighter,
  faKeyboard,
  faList,
  faPalette,
  faRobot,
  faShieldHalved,
  faTableCells,
  faTableColumns,
  faTowerBroadcast,
  faUser,
  faUserSecret,
  faUsers,
  faVideo,
  faWandMagicSparkles,
  faYoutube,
} from '../../common/icons/index.js';
import {SettingPanelIds} from './stores/SettingStore.jsx';

// Icon shown next to each setting in the side navigation. Sourced from the central
// icon registry (common/icons) so the Font Awesome fallback applies when Hugeicons
// Pro is unavailable at build time.
const SETTING_ICONS = {
  [SettingPanelIds.EMOTES]: faFaceSmile,
  [SettingPanelIds.THEME]: faPalette,
  [SettingPanelIds.EMOTE_MENU]: faBorderAll,
  [SettingPanelIds.EMOTE_AUTOCOMPLETE]: faWandMagicSparkles,
  [SettingPanelIds.AUTO_LIVE_CHAT_VIEW]: faTowerBroadcast,
  [SettingPanelIds.YOUTUBE]: faYoutube,
  [SettingPanelIds.WHISPERS]: faEnvelope,
  [SettingPanelIds.TAB_COMPLETION]: faKeyboard,
  [SettingPanelIds.SPLIT_CHAT]: faTableColumns,
  [SettingPanelIds.USERNAMES]: faUser,
  [SettingPanelIds.CHAT]: faComment,
  [SettingPanelIds.SIDEBAR]: faList,
  [SettingPanelIds.CHANNEL_POINTS]: faGem,
  [SettingPanelIds.RAIDS]: faUsers,
  [SettingPanelIds.PRIME_GAMING]: faCrown,
  [SettingPanelIds.DIRECTORY]: faCompass,
  [SettingPanelIds.PLAYER]: faVideo,
  [SettingPanelIds.MODERATION]: faShieldHalved,
  [SettingPanelIds.HIGHLIGHTS]: faHighlighter,
  [SettingPanelIds.DELETED_MESSAGES]: faCommentSlash,
  [SettingPanelIds.CHAT_LAYOUT]: faTableCells,
  [SettingPanelIds.BLACKLIST_KEYWORDS]: faBan,
  [SettingPanelIds.CHAT_DIRECTION]: faArrowsUpDown,
  [SettingPanelIds.ANON_CHAT]: faUserSecret,
  [SettingPanelIds.AUTO_PLAY]: faCirclePlay,
  [SettingPanelIds.AUTO_CLAIM]: faGift,
  [SettingPanelIds.CHATBOTS]: faRobot,
};

export default SETTING_ICONS;
