language: node_js
env:
- NODE_ENV=production
node_js:
- '6.6'
before_script:
- which gulp || npm install -g gulp
script: gulp
notifications:
  slack:
    secure: ZlbZ0agjSL/qKrkDJqUcuX6gXcUGWqgh+pIOJxaeo0opeT9RtbQTKgEQzUl1Mg6u4dkYPllUaL/kK+7YKOLIip/nkfurQ7VLeLeJMsV6875OGV4QtiSiqRjXPOqv3sIjK1ijgcAUpjFDmZlk3ZUQ/aW8FgJnZYUMKNeMGu+Lgwk=
  email: false
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/gulp
