module.exports = function (data) {
    return {
        //Developers and Supporters
        "night": { mod: true, tagType: "broadcaster", tagName: "<span style='color:#FFD700;'>Creator</span>", color: "#000;text-shadow: 0 0 10px #FFD700" },
        //Donations
        "gspwar": { mod: false, tagType: "admin", tagName: "EH?" },
        "nightmare": { mod: false, tagType: "broadcaster", tagName: "MLG" },
        "sour": { mod: false, tagType: "brown", tagName: "<span style='color:#FFE600;'>Saucy</span>", color: data.color+";text-shadow: 0 0 10px #FFD700" },
        "yorkyyork": { mod: false, tagType: "broadcaster", tagName: "Nerd" },
        "striker035": { mod: true, tagType: "admin", tagName: "MotherLover" },
        "dogs": { mod: true, tagType: "orange", tagName: "Smelly", nickname: "Dog" },
        "jruxdev": { mod: true, tagType: "bot", tagName: "MuttonChops" },
        "totally_cereal": { mod: true, tagType: "staff", tagName: "Fruity" },
        "virtz": { mod: true, tagType: "staff", tagName: "Perv" },
        "unleashedbeast": { mod: true, tagType: "admin", tagName: "<span style='color:black;'>Surface</span>" },
        "kona": { mod: true, tagType: "broadcaster", tagName: "KK" },
        "norfolk": { mod: true, tagType: "broadcaster", tagName: "Creamy" },
        "leftyben": { mod: true, tagType: "lefty", tagName: "&nbsp;" },
        "maximusloopus": { mod: true, tagType: "admin", tagName: "<span style='color:black;'>Hero</span>" },
        "nokz": { mod: true, tagType: "staff", tagName: "N47" },
        "blindfolded": { mod: true, tagType: "broadcaster", tagName: "iLag" },
        "jagrawr": { mod: true, tagType: "admin", tagName: "Jag" },
        "snorlaxitive": { mod: true, tagType: "purple", tagName: "King" },
        "excalibur": { mod: true, tagType: "staff", tagName: "Boss" },
        "chez_plastic": { mod: true, tagType: "staff", tagName: "Frenchy" },
        "frontiersman72": { mod: true, tagType: "admin", tagName: "TMC" },
        "dckay14": { mod: true, tagType: "admin", tagName: "Ginger" },
        "boogie_yellow": { mod: true, tagType: "orange", tagName: "Yellow" },
        "harksa": { mod: true, tagType: "orange", tagName: "Feet" },
        "lltherocksaysll": { mod: true, tagType: "broadcaster", tagName: "BossKey" },
        "melissa_loves_everyone": { mod: true, tagType: "purple", tagName: "Chubby", nickname: "Bunny" },
        "redvaloroso": { mod: true, tagType: "broadcaster", tagName: "Dio" },
        "slapage": { mod: true, tagType: "bot", tagName: "I aM" },
        "deano2518": { mod: true, tagType: "orange", tagName: "<span style='color:black;'>WWFC</span>" },
        "eternal_nightmare": { mod: true, tagType: "broadcaster", tagName: "Spencer", nickname: "Nickiforek" },
        "iivii_beauty": { mod: true, tagType: "purple", tagName: "Crave" },
        "theefrenzy": { mod: true, tagType: "staff", tagName: "Handsome" },
        "gennousuke69": { mod: true, tagType: "admin", tagName: "Evil" },
        "zebbazombies": { mod: true, tagType: "moderator", tagName: "Hugs" },
        "nobama12345": { mod: true, tagType: "broadcaster", tagName: "Señor" },
        "uleet": { mod: true, tagType: "moderator", tagName: "Taco" },
        "mrimjustaminorthreat": { mod: true, tagType: "staff", tagName: "<span style='color:pink;'>Major</span>", nickname: "mrimjustamajorthreat" },
        "sournothardcore": { mod: true, tagType: "brown", tagName: "<span style='color:#FFE600 !important;'>Saucy</span>", color: data.color+";text-shadow: 0 0 10px #FFD700" },
        //People
        "whitesammy": { mod: false, color: "white;text-shadow: 0 0 2px #000" },
        "mac027": { mod: true, tagType: "admin", tagName: "Hacks" },
        "vaughnwhiskey": { mod: true, tagType: "admin", tagName: "Bacon" },
        "socaldesigner": { mod: true, tagType: "broadcaster", tagName: "Legend" },
        "perfectorzy": { mod: true, tagType: "moderator", tagName: "Jabroni Ave" },
        "pantallideth1": { mod: true, tagType: "staff", tagName: "Windmill" },
        "mmjc": { mod: true, tagType: "admin", tagName: "m&m" },
        "hawkeyye": { mod: true, tagType: "broadcaster", tagName: "EnVy", nickname: "Hawkeye" },
        "the_chopsticks": { mod: true, tagType: "admin", tagName: "oZn" },
        "bacon_donut": { mod: true, tagType: "bacon", tagName: "&#8203;", nickname: "Donut" },
        "tacos": { mod: true, tagType: "taco", tagName: "&#8203;" },
        "sauce": { mod: true, tagType: "purple", tagName: "Drippin' Dat" },
        "thejokko": { mod: true, tagType: "purple", tagName: "Swede" },
        "missmiarose": { mod: true, tagType: "admin", tagName: "Lovely" },
        //Xmas
        "r3lapse": { mod: true, tagType: "staff", tagName: "Kershaw" },
        "im_tony_": { mod: true, tagType: "admin", tagName: "oZn" },
        "tips_": { mod: true, tagType: "staff", tagName: "241" },
        "papa_dot": { mod: true, tagType: "moderator", tagName: "v8" },
        "1danny1032": { mod: true, tagType: "admin", tagName: "1Bar" },
        "cvagts": { mod: true, tagType: "staff", tagName: "SRL" },
        "thesabe": { mod: true, tagType: "orange", tagName: "<span style='color:blue;'>Sabey</span>" },
        "kerviel_": { mod: true, tagType: "staff", tagName: "Almighty" },
        "ackleyman": { mod: true, tagType: "orange", tagName: "Ack" }
    };
};